services:
  php:
    image: dunglas/frankenphp
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVER_NAME=:${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./:/app/public
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  caddy_data:
  caddy_config:
